[project]
authors = ["Henry Schreiner <henryschreineriii@gmail.com>"]
channels = ["conda-forge"]
description = "A book about modern CMake"
name = "modern-cmake"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[feature.test.dependencies]
root_base = ">=6.26"
cmake = ">=3.15"
make = "*"
cxx-compiler = "*"
libboost-devel = "*"
git = "*"

[feature.test.tasks.test]
cmd = "cmake -Sexamples -Bbuild && cmake --build build -v && cmake --build build -t test"


[feature.build.dependencies]
python = "3.10"
jupyter-book = ">=1.0.2,<2"
imagemagick = "*"
make = "*"


[feature.build.tasks]
build = "jupyter-book build ."
pdf = "jupyter-book build . --builder pdflatex"

[environments]
test = ["test"]
build = ["build"]
